name: Run Pytest

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pipenv
        run: pip install --upgrade pip pipenv

      - name: Install dependencies with pipenv
        run: pipenv install --dev

      - name: Run Pytest
        run: pipenv run pytest
